# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - Dentistry-Coronado

on:
  push:
    branches:
      - main
    paths:
      - "starter/ContosoDentistryChatBot/**"
  workflow_dispatch:

env:
  AZURE_WEBAPP_PACKAGE_PATH: "starter/ContosoDentistryChatBot/"

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: "Dentistry-Coronado"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F3DE3B9AD9AA4E708B2BBB04F9E452E6 }}
          package: .
